# Generated by Django 4.1.4 on 2023-05-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nurse_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='duration',
        ),
    ]
