# Generated by Django 4.1.4 on 2023-05-04 05:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_department'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
