# Generated by Django 4.1.4 on 2023-05-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_checkeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkeddate',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
