# Generated by Django 4.2 on 2023-05-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_department'),
        ('hospital', '0003_checkeddate_checked_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckedDate',
            new_name='TurnCheckedDate',
        ),
    ]
