# Generated by Django 4.1.4 on 2023-05-04 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_department'),
        ('hospital', '0004_rename_checkeddate_turncheckeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='turncheckeddate',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
