# Generated by Django 4.1.4 on 2023-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='turncheckeddate',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('paid', 'paid'), ('submitted', 'submitted')], default='submitted', max_length=15),
        ),
    ]
